In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("/content/drive/MyDrive/Crop Yield Prediction Using Multimodal Data Fusion/Datasets/Custom_Crops_yield_Historical_Dataset.csv")

In [3]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50765 entries, 0 to 50764
Data columns (total 20 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Dist Code                  50765 non-null  int64
 1   Year                       50765 non-null  int64
 2   State Code                 50765 non-null  int64
 3   State Name                 50765 non-null  object
 4   Dist Name                  50765 non-null  object
 5   Crop                       50765 non-null  object
 6   Area_ha                    50765 non-null  float64
 7   Yield_kg_per_ha            50765 non-null  float64
 8   N_req_kg_per_ha            50765 non-null  float64
 9   P_req_kg_per_ha            50765 non-null  float64
 10  K_req_kg_per_ha            50765 non-null  float64
 11  Total_N_kg                 50765 non-null  float64
 12  Total_P_kg                 50765 non-null  float64
 13  Total_K_kg                 50765 non-null  float64
 14  Temperature_C              50765 non-null  int64
 15  Humidity_%                 50765 non-null  int64
 16  pH                         50765 non-null  float64
 17  Rainfall_mm                50765 non-null  int64
 18  Wind_Speed_m_s             50765 non-null  float64
 19  Solar_Radiation_MJ_m2_day  50765 non-null  int64
dtypes: float64(10), int64(7), object(3)
memory usage: 7.7+ MB
None

In [4]:
df.isnull().sum()

Dist Code                    0
Year                         0
State Code                   0
State Name                   0
Dist Name                    0
Crop                         0
Area_ha                      0
Yield_kg_per_ha              0
N_req_kg_per_ha              0
P_req_kg_per_ha              0
K_req_kg_per_ha              0
Total_N_kg                   0
Total_P_kg                   0
Total_K_kg                   0
Temperature_C                0
Humidity_%                   0
pH                           0
Rainfall_mm                  0
Wind_Speed_m_s               0
Solar_Radiation_MJ_m2_day    0
dtype: int64

In [5]:
selected_features = [
    'Year',
    'State Name',
    'Dist Name',
    'Crop',
    'Area_ha',
    'N_req_kg_per_ha',
    'P_req_kg_per_ha',
    'K_req_kg_per_ha',
    'Temperature_C',
    'Humidity_%',
    'pH',
    'Rainfall_mm',
    'Wind_Speed_m_s',
    'Solar_Radiation_MJ_m2_day',
    'Yield_kg_per_ha' # Target variable
]

df_selected = df[selected_features].copy()

print("Information about the DataFrame with selected features:")
display(df_selected.info())
print("\nFirst 5 rows of the selected DataFrame:")
display(df_selected.head())

Information about the DataFrame with selected features:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50765 entries, 0 to 50764
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Year                       50765 non-null  int64
 1   State Name                 50765 non-null  object
 2   Dist Name                  50765 non-null  object
 3   Crop                       50765 non-null  object
 4   Area_ha                    50765 non-null  float64
 5   N_req_kg_per_ha            50765 non-null  float64
 6   P_req_kg_per_ha            50765 non-null  float64
 7   K_req_kg_per_ha            50765 non-null  float64
 8   Temperature_C              50765 non-null  int64
 9   Humidity_%                 50765 non-null  int64
 10  pH                         50765 non-null  float64
 11  Rainfall_mm                50765 non-null  int64
 12  Wind_Speed_m_s             50765 non-null  float64
 13  Solar_Radiation_MJ_m2_day  50765 non-null  int64
 14  Yield_kg_per_ha            50765 non-null  float64
dtypes: float64(7), int64(5), object(3)
memory usage: 5.8+ MB

None

First 5 rows of the selected DataFrame:

,Year,State Name,Dist Name,Crop,Area_ha,N_req_kg_per_ha,P_req_kg_per_ha,K_req_kg_per_ha,Temperature_C,Humidity_%,pH,Rainfall_mm,Wind_Speed_m_s,Solar_Radiation_MJ_m2_day,Yield_kg_per_ha
0,1966,Chhattisgarh,Durg,rice,548000.0,8.43975,4.05108,7.42698,25,80,6.5,1200,2.0,18,337.59
1,1966,Chhattisgarh,Durg,maize,3000.0,18.00009,8.00004,11.33339,22,70,6.0,800,2.5,20,666.67
2,1966,Chhattisgarh,Durg,chickpea,54000.0,9.00000,5.00000,9.00000,20,60,6.5,600,1.5,16,500.00
3,1967,Chhattisgarh,Durg,rice,547000.0,18.69275,8.97252,16.44962,25,80,6.5,1200,2.0,18,747.71
4,1967,Chhattisgarh,Durg,maize,3000.0,27.00000,12.00000,17.00000,22,70,6.0,800,2.5,20,1000.00

In [9]:
import pandas as pd

# One-hot encode 'State Name' and 'Crop'
df_processed = pd.get_dummies(df_selected, columns=['Crop'], drop_first=True)

# Drop 'Dist Name'
df_processed = df_processed.drop(columns=['Dist Name'])

print("DataFrame information after one-hot encoding and dropping 'Dist Name' (without scaling):")
display(df_processed.info())
print("\nFirst 5 rows of the processed DataFrame:")
display(df_processed.head())

DataFrame information after one-hot encoding and dropping 'Dist Name' (without scaling):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50765 entries, 0 to 50764
Data columns (total 16 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Year                       50765 non-null  int64
 1   State Name                 50765 non-null  object
 2   Area_ha                    50765 non-null  float64
 3   N_req_kg_per_ha            50765 non-null  float64
 4   P_req_kg_per_ha            50765 non-null  float64
 5   K_req_kg_per_ha            50765 non-null  float64
 6   Temperature_C              50765 non-null  int64
 7   Humidity_%                 50765 non-null  int64
 8   pH                         50765 non-null  float64
 9   Rainfall_mm                50765 non-null  int64
 10  Wind_Speed_m_s             50765 non-null  float64
 11  Solar_Radiation_MJ_m2_day  50765 non-null  int64
 12  Yield_kg_per_ha            50765 non-null  float64
 13  Crop_cotton                50765 non-null  bool
 14  Crop_maize                 50765 non-null  bool
 15  Crop_rice                  50765 non-null  bool
dtypes: bool(3), float64(7), int64(5), object(1)
memory usage: 5.2+ MB

None

First 5 rows of the processed DataFrame:

,Year,State Name,Area_ha,N_req_kg_per_ha,P_req_kg_per_ha,K_req_kg_per_ha,Temperature_C,Humidity_%,pH,Rainfall_mm,Wind_Speed_m_s,Solar_Radiation_MJ_m2_day,Yield_kg_per_ha,Crop_cotton,Crop_maize,Crop_rice
0,1966,Chhattisgarh,548000.0,8.43975,4.05108,7.42698,25,80,6.5,1200,2.0,18,337.59,False,False,True
1,1966,Chhattisgarh,3000.0,18.00009,8.00004,11.33339,22,70,6.0,800,2.5,20,666.67,False,True,False
2,1966,Chhattisgarh,54000.0,9.00000,5.00000,9.00000,20,60,6.5,600,1.5,16,500.00,False,False,False
3,1967,Chhattisgarh,547000.0,18.69275,8.97252,16.44962,25,80,6.5,1200,2.0,18,747.71,False,False,True
4,1967,Chhattisgarh,3000.0,27.00000,12.00000,17.00000,22,70,6.0,800,2.5,20,1000.00,False,True,False

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
print("Unique values for 'State Name':", df_selected['State Name'].unique())
print("\nUnique values for 'Dist Name':", df_selected['Dist Name'].unique())
print("\nUnique values for 'Crop':", df_selected['Crop'].unique())

Unique values for 'State Name': ['Chhattisgarh' 'Madhya Pradesh' 'Andhra Pradesh' 'Telangana' 'Karnataka'
 'Tamil Nadu' 'Maharashtra' 'Gujarat' 'Rajasthan' 'Punjab' 'Haryana'
 'Uttar Pradesh' 'Uttarakhand' 'Assam' 'Himachal Pradesh' 'Kerala'
 'Orissa' 'West Bengal' 'Bihar' 'Jharkhand']

Unique values for 'Dist Name': ['Durg' 'Bastar' 'Raipur' 'Bilaspur' 'Raigarh' 'Surguja' 'Jabalpur'
 'Balaghat' 'Chhindwara' 'Narsinghpur' 'Seoni / Shivani' 'Mandla' 'Sagar'
 'Damoh' 'Tikamgarh' 'Chhatarpur' 'Panna' 'Rewa' 'Sidhi' 'Satna' 'Shahdol'
 'Gwalior' 'Shivpuri' 'Guna' 'Datia' 'Morena' 'Bhind' 'Indore' 'Ratlam'
 'Ujjain' 'Mandsaur' 'Dewas' 'Dhar' 'Jhabua' 'Khargone / West Nimar'
 'Khandwa / East Nimar' 'Sehore' 'Raisen' 'Vidisha' 'Betul' 'Rajgarh'
 'Shajapur' 'Hoshangabad' 'Srikakulam' 'Visakhapatnam' 'East Godavari'
 'West Godavari' 'Krishna' 'Guntur' 'S.P.S. Nellore' 'Kurnool'
 'Ananthapur' 'Kadapa YSR' 'Chittoor' 'Hyderabad' 'Nizamabad' 'Medak'
 'Mahabubnagar' 'Nalgonda' 'Warangal' 'Khammam' 'Karimnagar' 'Adilabad'
 'Bangalore' 'Kolar' 'Tumkur' 'Mysore' 'Mandya' 'Hassan' 'Shimoge'
 'Chickmagalur' 'Chitradurga' 'Bellary' 'Dharwad' 'Belgaum'
 'Bijapur / Vijayapura' 'Bidar' 'Raichur' 'Gulbarga / Kalaburagi'
 'Dakshina Kannada' 'Uttara Kannada' 'Kodagu / Coorg'
 'Chengalpattu MGR / Kanchipuram' 'South Arcot / Cuddalore'
 'North Arcot / Vellore' 'Salem' 'Coimbatore' 'Tiruchirapalli / Trichy'
 'Thanjavur' 'Madurai' 'Ramananthapuram' 'Thirunelveli' 'The Nilgiris'
 'Kanyakumari' 'Bombay' 'Thane' 'Raigad' 'Ratnagiri' 'Nasik' 'Dhule'
 'Jalgaon' 'Ahmednagar' 'Pune' 'Satara' 'Sangli' 'Solapur' 'Kolhapur'
 'Aurangabad' 'Parbhani' 'Beed' 'Nanded' 'Osmanabad' 'Buldhana' 'Akola'
 'Amarawati' 'Yeotmal' 'Wardha' 'Nagpur' 'Bhandara' 'Chandrapur'
 'Ahmedabad' 'Amreli' 'Banaskantha' 'Bharuch' 'Vadodara / Baroda'
 'Bhavnagar' 'Valsad' 'Dangs' 'Jamnagar' 'Junagadh' 'Kheda' 'Kutch'
 'Mehsana' 'Panchmahal' 'Rajkot' 'Sabarkantha' 'Surat' 'Surendranagar'
 'Ajmer' 'Alwar' 'Banswara' 'Barmer' 'Bharatpur' 'Bhilwara' 'Bikaner'
 'Bundi' 'Chittorgarh' 'Churu' 'Dungarpur' 'Ganganagar' 'Jaipur'
 'Jaisalmer' 'Jalore' 'Jhalawar' 'Jhunjhunu' 'Jodhpur' 'Kota' 'Nagaur'
 'Pali' 'Swami Madhopur' 'Sikar' 'Sirohi' 'Tonk' 'Udaipur' 'Gurdaspur'
 'Amritsar' 'Kapurthala' 'Jalandhar' 'Hoshiarpur' 'Roopnagar / Ropar'
 'Ludhiana' 'Ferozpur' 'Bhatinda' 'Sangrur' 'Patiala' 'Hissar' 'Gurgaon'
 'Jind' 'Mahendragarh / Narnaul' 'Ambala' 'Karnal' 'Rohtak' 'Saharanpur'
 'Muzaffarnagar' 'Meerut' 'Buland Shahar' 'Aligarh' 'Mathura' 'Agra'
 'Mainpuri' 'Etah' 'Bareilly' 'Budaun' 'Moradabad' 'Shahjahanpur'
 'Pilibhit' 'Rampur' 'Bijnor' 'Farrukhabad' 'Etawah' 'Kanpur' 'Fatehpur'
 'Allahabad' 'Jhansi' 'Jalaun' 'Hamirpur' 'Banda' 'Varanasi' 'Mirzpur'
 'Jaunpur' 'Ghazipur' 'Ballia' 'Gorakhpur' 'Deoria' 'Basti' 'Azamgarh'
 'Lucknow' 'Unnao' 'Rae-Bareily' 'Sitapur' 'Hardoi' 'Kheri' 'Faizabad'
 'Gonda' 'Bahraich' 'Sultanpur' 'Pratapgarh' 'Barabanki' 'Nainital'
 'Almorah' 'Pithorgarh' 'Chamoli' 'Uttar Kashi' 'Tehri Garhwal' 'Garhwal'
 'Dehradun' 'Cachar' 'Darrang' 'Dibrugarh' 'Goalpara' 'Kamrup'
 'Karbi Anglong' 'Lakhimpur' 'North Cachar Hil / Dima hasao' 'Nagaon'
 'Sibsagar' 'Bilashpur' 'Chamba' 'Kangra' 'Kinnaur' 'Kullu'
 'Lahul & Spiti' 'Solan' 'Mandi' 'Shimla' 'Sirmaur' 'Alappuzha' 'Kannur'
 'Eranakulam' 'Kottayam' 'Kozhikode' 'Malappuram' 'Palakkad' 'Kollam'
 'Thrissur' 'Thiruvananthapuram' 'Balasore' 'Bolangir' 'Cuttack'
 'Dhenkanal' 'Ganjam' 'Kalahandi' 'Keonjhar' 'Koraput' 'Mayurbhanja'
 'Phulbani ( Kandhamal )' 'Puri' 'Sambalpur' 'Sundargarh' '24 Parganas'
 'Nadia' 'Murshidabad' 'Burdwan' 'Birbhum' 'Bankura' 'Hooghly' 'Howrah'
 'Jalpaiguri' 'Darjeeling' 'Malda' 'Cooch Behar' 'Purulia' 'Midnapur'
 'West Dinajpur' 'Champaran' 'Muzaffarpur' 'Darbhanga' 'Saharsa' 'Purnea'
 'Saran' 'Patna' 'Mungair' 'Bhagalpur' 'Santhal Paragana / Dumka'
 'Shahabad (now part of Bhojpur district)' 'Gaya' 'Hazaribagh' 'Dhanbad'
 'Palamau' 'Ranchi' 'Singhbhum']

Unique values for 'Crop': ['rice' 'maize' 'chickpea' 'cotton']

In [12]:
# Define the path to save the cleaned dataset
output_path = "/content/drive/MyDrive/Crop Yield Prediction Using Multimodal Data Fusion/Datasets/Cleaned_Crops_yield_Historical_Dataset.csv"

# Save the DataFrame to a CSV file
df_processed.to_csv(output_path, index=False)

print(f"Cleaned dataset saved successfully to: {output_path}")

# You can load it back later using:
# df_cleaned = pd.read_csv(output_path)

Cleaned dataset saved successfully to: /content/drive/MyDrive/Crop Yield Prediction Using Multimodal Data Fusion/Datasets/Cleaned_Crops_yield_Historical_Dataset.csv